Repository TYPO3BestPractices/tea, pull requests merged in 2019-12, with the labels that each got.

#19 [TASK] Rename TS files to .typoscript
  CHANGELOG.md
  Configuration/TypoScript/constants.typoscript
  Configuration/TypoScript/setup.typoscript
  Tests/Functional/Controller/TeaControllerTest.php
Labels: cleanup

#23 Fix codesniffer issues
  CHANGELOG.md
  Classes/Controller/TeaController.php
  Classes/Domain/Model/Product/Tea.php
  Classes/Domain/Repository/Product/TeaRepository.php
  Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
  Tests/Acceptance/StarterCest.php
  Tests/Acceptance/_support/AcceptanceTester.php
  Tests/Acceptance/_support/Helper/Acceptance.php
  Tests/Functional/Controller/TeaControllerTest.php
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
  Tests/Unit/Controller/TeaControllerTest.php
  Tests/Unit/Domain/Model/Product/TeaTest.php
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
  composer.json
Labels: bug, cleanup

#29 [BUGFIX] Update the badge URLs in the README
  CHANGELOG.md
  README.md
Labels: bug, documentation

#33 [TASK] Add a status badge for GitHub actions
  CHANGELOG.md
  README.md
Labels: enhancement

#34 [TASK] Drop obsolete parts from the README
  CHANGELOG.md
  README.md
Labels: cleanup, documentation

#35 [TASK] Switch the code sniffing from PSR-2 to PSR-12
  CHANGELOG.md
  Tests/Unit/Controller/TeaControllerTest.php
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
  composer.json
  phpcs.xml.dist
Labels: cleanup

#39 [BUGFIX] Keep the global namespace clean in ext_localconf.php
  CHANGELOG.md
  ext_localconf.php
Labels: bug, cleanup

#41 [BUGFIX] Re-add the static TypoScript registration
  CHANGELOG.md
  Configuration/TCA/Overrides/sys_template.php
Labels: bug
