Repository TYPO3BestPractices/tea, pull requests merged in 2020-11, with the labels that each got.

#156 Migrate secret detection in gitlab ci
  .gitlab/pipeline/.gitlab-ci.yml
Labels: bug

#158 Fix to gitlab regression
  .gitlab/pipeline/.gitlab-ci.yml
Labels: bug

#148 [TASK] Add feature list
  README.md
Labels: documentation

#160 [FEATURE] Also run the CI build once a week
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: enhancement

#164 [CLEANUP] Polish the comments in .editorconfig
  .editorconfig
Labels: cleanup

#165 [BUGFIX] Stop treating *.ts files as TypoScript in the .editorconfig
  .editorconfig
Labels: bug

#166 [FEATURE] Add a configuration for XML files to the .editorconfig
  .editorconfig
Labels: enhancement

#168 [CLEANUP] Consistently quote all CI step names for GitHub actions
  .github/workflows/ci.yml
Labels: cleanup

#170 [BUGFIX] Fix the CI build with the lowest dependencies
  .github/workflows/ci.yml
  composer.json
Labels: bug

#172 [CLEANUP] Explicitly set the Ubuntu version for most CI steps
  .github/workflows/ci.yml
Labels: cleanup

#162 [BUGFIX] Explicitly set the Ubuntu version for GitHub Actions
  .github/workflows/ci.yml
Labels: bug, cleanup

#174 [BUGFIX] Fix cache keys for the Composer cache in GitHub Actions
  .github/workflows/ci.yml
Labels: bug

#178 [CLEANUP] Sort the lines in the .gitignore and .gitattributes
  .gitattributes
  .gitignore
Labels: cleanup

#177 [FEATURE] Adopt the stylelint configuration from the TYPO3 Core
  Resources/Private/stylelint.config.js
  Resources/Public/Css/Main.css
Labels: cleanup

#157 Prepare documentation rendering
  .gitignore
  Documentation/Documentation/Rendering/Index.rst
  Documentation/Includes.txt
  Documentation/Index.rst
  Documentation/Introduction/Index.rst
  Documentation/Settings.cfg
  Documentation/Sitemap.rst
  README.md
Labels: documentation, enhancement

#176 [CLEANUP] Adopt .editorconfig settings from the TYPO3 core
  .editorconfig
  Resources/Public/JavaScript/Main.js
Labels: bug, cleanup
