Repository TYPO3BestPractices/tea, pull requests merged in 2020-12, with the labels that each got.

#179 [CLEANUP] Adapt the TypoScript lint settings to the .editorconfig set…
  Configuration/TsLint.yml
  Configuration/TypoScript/Frontend/setup.typoscript
  Configuration/TypoScript/constants.typoscript
  Configuration/TypoScript/setup.typoscript
Labels: cleanup

#175 [CLEANUP] Autoformat all files
  .github/workflows/ci.yml
  .gitlab/pipeline/.gitlab-ci.yml
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TsLint.yml
  Resources/Private/.eslintrc.json
  Resources/Private/.prettierrc.js
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_db.xlf
  Resources/Private/Templates/Tea/Index.html
  Resources/Private/package.json
  Resources/Private/stylelint.config.js
  codeception.yml
  composer.json
  ext_tables.sql
Labels: cleanup

#180 Fix to copypaste check for gitlab ci
  .gitlab/pipeline/.gitlab-ci.yml
Labels: bug

#181 [FEATURE] Add frontend linting to GitLab CI
  .gitlab/pipeline/.gitlab-ci.yml
Labels: enhancement

#182 [CLEANUP] Sort the requirements in the composer.json
  composer.json
Labels: cleanup

#183 [TASK] Remove code quality job from GitLab CI template
  .gitlab/pipeline/.gitlab-ci.yml
Labels: cleanup
