Repository TYPO3BestPractices/tea, pull requests merged in 2020-10, with the labels that each got.

#108 [TASK] Add gitlab ci badge
  README.md
Labels: documentation, enhancement

#112 [TASK] Rename dist files
  .gitattributes
  .php_cs.php
  composer.json
  phpcs.xml
Labels: cleanup

#111 [TASK] Remove security checker
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: cleanup

#118 [BUGFIX] Only show the default branch status in the CI badge
  README.md
Labels: bug, documentation

#119 [BUGFIX] Always use the configuration file for php-cs-fixer
  composer.json
Labels: bug

#122 [TASK] Sniff and codestyle fix to php in configuration dir
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TCA/tx_tea_domain_model_product_tea.php
Labels: cleanup

#151 [BUGFIX] Fix a typo in a CI status badge alt text
  README.md
Labels: bug, documentation

#153 [BUGFIX] Drop a surplus hyphen in the CI step definitions
  .github/workflows/ci.yml
Labels: bug

#147 [TASK] Add one command to do sniffers and fixers
  composer.json
Labels: cleanup

#152 [TASK] Smoothen the way to Composer 2
  .github/workflows/ci.yml
  .gitlab/pipeline/.gitlab-ci.yml
Labels: bug
