Repository TYPO3BestPractices/tea, pull requests merged in 2021-05, with the labels that each got.

#243 [TASK] Add code of conduct badge to README
  README.md
Labels: documentation

#239 [TASK] Migrate the PHPStan check to GitHub actions
  .github/workflows/ci.yml
Labels: cleanup

#251 [TASK] Limit the line length for Markdown files via `.editorconfig`
  .editorconfig
Labels: documentation

#254 [BUGFIX] Add conflict for doctrine/dbal
  composer.json
Labels: bug

#234 [FEATURE] Add base ddev setup and command
  .ddev/config.yaml
  README.md
Labels: enhancement

#247 [BUGFIX] Fix phpcs fix script
  composer.json
  phive.xml
  tools/phpcbf
Labels: bug
