Repository TYPO3BestPractices/tea, pull requests merged in 2021-09, with the labels that each got.

#294 [TASK] Remove author annotations
  Classes/Controller/TeaController.php
  Classes/Domain/Model/Product/Tea.php
  Classes/Domain/Repository/Product/TeaRepository.php
  Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
  Tests/Acceptance/StarterCest.php
  Tests/Functional/Controller/TeaControllerTest.php
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
  Tests/Unit/Controller/TeaControllerTest.php
  Tests/Unit/Domain/Model/Product/TeaTest.php
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#304 [BUGFIX] Complete the `typo3/cms` section in the `composer.json`
  composer.json
Labels: bug

#299 [CLEANUP] Fix the Prophecy-related type annotations
  Tests/Unit/Controller/TeaControllerTest.php
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#309 [TASK] Exclude ddev directory
  .gitattributes
  composer.json
Labels: cleanup

#293 [TASK] Start to work on TYPO3 v11 support
  .github/workflows/ci.yml
  composer.json
  ext_emconf.php
Labels: enhancement

#311 [TASK] Add php8 compatibility
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/php-lint-php8.0.yml
  composer.json
Labels: enhancement
