Repository TYPO3BestPractices/tea, pull requests merged in 2021-08, with the labels that each got.

#272 [TASK] Update phive tools and cleanup
  phive.xml
Labels: cleanup

#270 [TASK] Completely rewrite the README
  README.md
Labels: documentation

#277 [FEATURE] Composer command for rendering documentation
  README.md
  composer.json
Labels: enhancement

#284 [TASK] Move the Composer script descriptions to the `composer.json`
  README.md
  composer.json
Labels: documentation, enhancement, cleanup

#273 [TASK] Split GitLab jobs
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/.default-frontend.yml
  .gitlab/pipeline/jobs/.default.yml
  .gitlab/pipeline/jobs/.variables.yml
  .gitlab/pipeline/jobs/build-composer-dependencies.yml
  .gitlab/pipeline/jobs/composer-normalize.yml
  .gitlab/pipeline/jobs/func-php7.2-v10.yml
  .gitlab/pipeline/jobs/func-php7.2-v9.yml
  .gitlab/pipeline/jobs/func-php7.3-v10.yml
  .gitlab/pipeline/jobs/func-php7.3-v9.yml
  .gitlab/pipeline/jobs/func-php7.4-v10.yml
  .gitlab/pipeline/jobs/func-php7.4-v9.yml
  .gitlab/pipeline/jobs/javascript-lint.yml
  .gitlab/pipeline/jobs/json-lint.yml
  .gitlab/pipeline/jobs/php-copypaste-check.yml
  .gitlab/pipeline/jobs/php-lint-php7.2.yml
  .gitlab/pipeline/jobs/php-lint-php7.3.yml
  .gitlab/pipeline/jobs/php-lint-php7.4.yml
  .gitlab/pipeline/jobs/phpcs.yml
  .gitlab/pipeline/jobs/phpstan.yml
  .gitlab/pipeline/jobs/ts-lint.yml
  .gitlab/pipeline/jobs/unit-php7.2-v10.yml
  .gitlab/pipeline/jobs/unit-php7.2-v9.yml
  .gitlab/pipeline/jobs/unit-php7.3-v10.yml
  .gitlab/pipeline/jobs/unit-php7.3-v9.yml
  .gitlab/pipeline/jobs/unit-php7.4-v10.yml
  .gitlab/pipeline/jobs/unit-php7.4-v9.yml
  .gitlab/pipeline/jobs/xliff-lint.yml
  .gitlab/pipeline/jobs/yaml-lint.yml
Labels: cleanup
