Repository TYPO3BestPractices/tea, pull requests merged in 2021-10, with the labels that each got.

#312 [TASK] Add PhpStorm meta file
  .phpstorm.meta.php
Labels: enhancement, cleanup

#314 [TASK] Add support for TYPO3 11.5
  composer.json
Labels: enhancement

#317 [CLEANUP] Polish the PhpStorm meta file
  .phpstorm.meta.php
Labels: cleanup

#266 [FEATURE] Calculate code coverage
  .ddev/php/custom-php.ini
  .github/workflows/codecoverage.yml
  .gitignore
  README.md
  composer.json
  phive.xml
  tools/phpcov
Labels: enhancement

#323 [FEATURE] Re-allow installations on TYPO3 11LTS
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: enhancement
