Repository TYPO3BestPractices/tea, pull requests merged in 2021-02, with the labels that each got.

#191 Normalize composer json file
  composer.json
Labels: cleanup

#194 Fixes to readme
  README.md
Labels: cleanup

#195 Update urls in composer json
  composer.json
Labels: cleanup

#190 Use PHPCPD as phar instead of composer package
  .gitattributes
  composer.json
  phive.xml
  tools/phive.phar
  tools/phpcpd.phar
Labels: cleanup

#196 Migrate phpcs to phar
  composer.json
  phive.xml
  tools/phpcs.phar
Labels: cleanup

#197 Update README.md
  README.md
Labels: documentation, enhancement

#189 [FEATURE] Add TER release via github actions
  .github/workflows/publish.yml
  composer.json
Labels: enhancement

#199 [TASK] Migrate php-cs-fixer to phive
  composer.json
  phive.xml
  tools/php-cs-fixer.phar
Labels: cleanup

#200 [TASK] Migrate typoscript linter to phive
  composer.json
  phive.xml
  tools/typo3-typoscript-lint.phar
Labels: cleanup

#209 [BUGFIX] Use correct relative paths for removing files from release
  composer.json
Labels: bug

#208 [BUGFIX] Stop packaging the PHIVE configuration file and tools
  .gitattributes
  composer.json
Labels: bug

#210 [CLEANUP] Drop the reflection docblock dev dependency
  composer.json
Labels: cleanup

#206 [BUGFIX] Downgrade the XLIFF files to version 1.0
  .github/workflows/ci.yml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_db.xlf
Labels: bug
