Repository TYPO3BestPractices/tea, pull requests merged in 2021-03, with the labels that each got.

#215 Exclude node modules from yarn lint
  composer.json
Labels: bug

#216 [TASK] Update the manual URL in the README
  README.md
Labels: documentation

#220 [TASK] Migrate TypoScript linting to a GitHub action
  .github/workflows/ci.yml
Labels: cleanup

#221 [TASK] Migrate to yaml linter github actions
  .github/workflows/ci.yml
Labels: cleanup

#222 [TASK] Migrate copy'n'paste detector to GitHub actions
  .github/workflows/ci.yml
Labels: cleanup

#227 [CLEANUP] Rename the CS fixer composer script
  .github/workflows/ci.yml
  README.md
  composer.json
Labels: cleanup
