Repository TYPO3BestPractices/tea, pull requests merged in 2021-11, with the labels that each got.

#329 [BUGFIX] Only publish to the TER if the tag is a valid version number
  .github/workflows/publish.yml
  CHANGELOG.md
Labels: bug

#331 [TASK] Upgrade ddev to v1.18.0
  .ddev/config.yaml
Labels: cleanup

#335 [BUGFIX] Require at least TYPO3 11.5.2 for 11LTS
  CHANGELOG.md
  composer.json
Labels: bug

#341 [TASK] Fix php according to official php cs configuration
  Classes/Controller/TeaController.php
  Classes/Domain/Model/Product/Tea.php
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
  Tests/Unit/Controller/TeaControllerTest.php
  Tests/Unit/Domain/Model/Product/TeaTest.php
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
  ext_emconf.php
  ext_localconf.php
Labels: cleanup

#340 [TASK] Migrate to typo3 coding standards
  .gitattributes
  .php-cs-fixer.php
  .php_cs.php
  composer.json
Labels: enhancement

#343 [TASK] Add badges to readme
  README.md
Labels: documentation, enhancement
