Repository TYPO3BestPractices/tea, pull requests merged in 2021-07, with the labels that each got.

#262 [TASK] Upgrade to CoC v2
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#258 [TASK] Add separate workflow for composer scripts
  .github/workflows/ci-composer-scripts.yml
  Documentation/Index.rst
  Documentation/Linters/GitHub/Index.rst
  Documentation/Linters/GitLab/Index.rst
  Documentation/Linters/Index.rst
  README.md
Labels: cleanup

#259 [TASK] Run functional tests in ddev
  .ddev/config.yaml
  README.md
Labels: enhancement

#271 [BUGFIX] Fix default template names for GitLab CI
  .gitlab/pipeline/.gitlab-ci.yml
Labels: bug
