Repository TYPO3BestPractices/tea, pull requests merged in 2022-10, with the labels that each got.

#597 [TASK] Return `ResponseInterface` in controller actions
  CHANGELOG.md
  Classes/Controller/TeaController.php
  Tests/Unit/Controller/TeaControllerTest.php
Labels: bug, cleanup

#599 [CLEANUP] Use typed properties instead of `@var` annotations
  CHANGELOG.md
  Classes/Controller/TeaController.php
  Classes/Domain/Model/Product/Tea.php
  Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
  Tests/Unit/Domain/Model/Product/TeaTest.php
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#604 [BUGFIG] Add functional tests for v11 for gitlab
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/func-php7.4-v11.yml
  .gitlab/pipeline/jobs/func-php8.0-v11.yml
  .gitlab/pipeline/jobs/func-php8.1-v11.yml
Labels: bug, enhancement

#606 Fix typo in functional tests needs in gitlab
  .gitlab/pipeline/jobs/func-php8.1-v11.yml
Labels: bug

#611 [CLEANUP] Drop some redundant PHPDoc type annotations
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#612 [CLEANUP] Add more native type annotations in the tests
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#613 [BUGFIX] Stop relying on transitive dependencies for `psr/http-message`
  CHANGELOG.md
  composer.json
Labels: bug, dependencies

#617 [TASK] Have the lowest dependencies above the highest on CI
  .github/workflows/ci.yml
Labels: cleanup

#619 [TASK] Have the lowest dependencies above the highest on CI
  .github/workflows/predefined.yml
Labels: cleanup

#621 [TASK] Upgrade `friendsofphp/php-cs-fixer`
  composer.json
Labels: dependencies

#622 [TASK] Bump the Symfony dependencies
  CHANGELOG.md
  composer.json
Labels: dependencies

#620 [TASK] Remove obsolete Composer conflicts
  composer.json
Labels: cleanup, dependencies

#623 [TASK] Have the lowest dependencies above the highest on CI
  .github/workflows/predefined.yml
Labels: cleanup

#616 [CLEANUP] Drop usages of `ObjectManager` whereever possible
  Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#628 [CLEANUP] Use more native property types in the tests
  CHANGELOG.md
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#627 [BUGFIX] Exclude `doctrine/dbal` from Dependabot updates
  .github/dependabot.yml
Labels: bug, dependencies

#625 [TASK] Make the TCA ready for TYPO3 v12
  CHANGELOG.md
  Configuration/TCA/tx_tea_domain_model_product_tea.php
Labels: cleanup

#629 [TASK] Upgrade to the testing framework V7
  CHANGELOG.md
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
  composer.json
Labels: dependencies

#633 [BUGFIX] Fix the license badge in the README
  README.md
Labels: bug, documentation

#636 [TASK] Add the testing framework bridge as dev dependency
  composer.json
Labels: dependencies

#637 [FEATURE] Allow installations with TYPO3 12LTS
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: enhancement, dependencies

#639 [TASK] Postpone the TYPO3 12 compatibility
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: dependencies

#645 [TASK] Upgrade to `helmich/typo3-typoscript-lint` V3
  CHANGELOG.md
  composer.json
Labels: dependencies

#643 [BUGFIX] Raise `typo3/cms-*` to 11.5.4 to be stable with minimum deps
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: bug, dependencies

#641 [BUGFIX] Do not check `composer.lock` during `composer normalize`
  CHANGELOG.md
  composer.json
Labels: bug

#650 Stop injecting query settings
  CHANGELOG.md
  Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
Labels: bug

#655 [TASK] Add lowest and highest dependencies to gitlab ci
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/func-php7.4-v11-highest.yml
  .gitlab/pipeline/jobs/func-php7.4-v11-lowest.yml
  .gitlab/pipeline/jobs/func-php8.0-v11-highest.yml
  .gitlab/pipeline/jobs/func-php8.0-v11-lowest.yml
  .gitlab/pipeline/jobs/func-php8.1-v11-highest.yml
  .gitlab/pipeline/jobs/func-php8.1-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php7.4-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php7.4-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php7.4-v11.yml
  .gitlab/pipeline/jobs/unit-php8.0-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php8.0-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.0-v11.yml
  .gitlab/pipeline/jobs/unit-php8.1-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v11.yml
Labels: enhancement

#649 Harden Github Actions workflows
  .github/workflows/ci.yml
  .github/workflows/codecoverage.yml
  .github/workflows/predefined.yml
  .github/workflows/publish.yml
  CHANGELOG.md
Labels: enhancement

#653 [FEATURE] Run the unit tests on TYPO3 12 on CI
  .github/workflows/ci.yml
  .github/workflows/predefined.yml
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-lowest.yml
  CHANGELOG.md
Labels: enhancement

#654 [TASK] Document our approach to PHP version support
  Documentation/Index.rst
  Documentation/PHPVersionSupport.rst
Labels: documentation

#615 [FEATURE] Run the functional tests on TYPO3 12 as well
  .github/workflows/ci.yml
  .github/workflows/predefined.yml
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml
  CHANGELOG.md
Labels: enhancement

#657 [TASK] Avoid race condition on case-insensitive filesystems
  .github/workflows/codecoverage.yml
  .gitignore
  CHANGELOG.md
  composer.json
Labels: bug
