Repository TYPO3BestPractices/tea, pull requests merged in 2022-08, with the labels that each got.

#504 [BUGFIX] Correct version constraints for PHP in composer.json
  composer.json
Labels: bug

#511 [BUGFIX] Explicitly require Prophecy
  CHANGELOG.md
  composer.json
Labels: bug

#514 [BUGFIX] Bump the minimal 10.4 Extbase requirement
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: bug

#515 [BUGFIX] Have all extension dependencies in the `ext_emconf.php` as well
  CHANGELOG.md
  ext_emconf.php
Labels: bug

#523 [TASK] Use CamelCase for the TsConfig folder
  CHANGELOG.md
  Configuration/TsConfig/Page/.gitkeep
  Configuration/TsConfig/User/.gitkeep
Labels: cleanup

#524 [TASK] Allow dev installations with Doctrine 3
  composer.json
Labels: dependencies

#531 [TASK] Stop using the `typo3/minimal` package on CI
  .gitlab/pipeline/jobs/func-php7.2-v10.yml
  .gitlab/pipeline/jobs/func-php7.3-v10.yml
  .gitlab/pipeline/jobs/func-php7.4-v10.yml
  .gitlab/pipeline/jobs/unit-php7.2-v10.yml
  .gitlab/pipeline/jobs/unit-php7.3-v10.yml
  .gitlab/pipeline/jobs/unit-php7.4-v10.yml
  CHANGELOG.md
Labels: bug
