Repository TYPO3BestPractices/tea, pull requests merged in 2022-07, with the labels that each got.

#480 [BUGFIX] Do not overwrite type annotations from parent classes
  Classes/Domain/Repository/Product/TeaRepository.php
  phpstan-baseline.neon
Labels: bug, cleanup

#477 [TASK] Add Slack to README
  README.md
Labels: documentation

#481 [FEATURE] Configure Dependabot to also update npm packages
  .github/dependabot.yml
  CHANGELOG.md
Labels: enhancement
