Repository TYPO3BestPractices/tea, pull requests merged in 2022-03, with the labels that each got.

#399 [BUGFIX] Configure DI and avoid using `ObjectManager` in TYPO3 11LTS
  Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
  Configuration/Services.yaml
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: bug, enhancement

#319 [FEATURE] Also run the tests with TYPO3 11LTS in GitHub Actions
  .github/workflows/ci.yml
Labels: enhancement

#411 [BUGFIX] Remove folders `Config` and `Tests` from phpcpd call
  composer.json
Labels: bug

#415 [CLEANUP] Make a type annotation more specific
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup
