Repository TYPO3BestPractices/tea, pull requests merged in 2022-02, with the labels that each got.

#373 [BUGFIX] install and use wait-for-it for functional tests
  .gitlab/build/docker_install.sh
  .gitlab/pipeline/jobs/func-php7.2-v10.yml
  .gitlab/pipeline/jobs/func-php7.2-v9.yml
  .gitlab/pipeline/jobs/func-php7.3-v10.yml
  .gitlab/pipeline/jobs/func-php7.3-v9.yml
  .gitlab/pipeline/jobs/func-php7.4-v10.yml
  .gitlab/pipeline/jobs/func-php7.4-v9.yml
Labels: bug

#374 Disable predefined github action scheduler run
  .github/workflows/predefined.yml
Labels: cleanup

#375 [BUGFIX] Fix some `.gitignore` entries
  .gitignore
Labels: bug

#379 [TASK] Drop TeaController functional test
  Tests/Functional/Controller/Fixtures/Database/pages.xml
  Tests/Functional/Controller/Fixtures/Frontend/Basic.typoscript
  Tests/Functional/Controller/Fixtures/Frontend/Template.html
  Tests/Functional/Controller/TeaControllerTest.php
Labels: cleanup

#380 [TASK] Drop v9 support in gitlab ci
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/func-php7.2-v9.yml
  .gitlab/pipeline/jobs/func-php7.3-v9.yml
  .gitlab/pipeline/jobs/func-php7.4-v9.yml
  .gitlab/pipeline/jobs/unit-php7.2-v9.yml
  .gitlab/pipeline/jobs/unit-php7.3-v9.yml
  .gitlab/pipeline/jobs/unit-php7.4-v9.yml
Labels: cleanup

#386 [BUGFIX] Remove `showRecordFieldList` from the TCA
  Configuration/TCA/tx_tea_domain_model_product_tea.php
Labels: bug

#385 [BUGFIX] Stop using the vendor name for plugin registration
  Configuration/TCA/Overrides/tt_content.php
  ext_localconf.php
Labels: bug

#389 [TASK] Remove an obsolete version switch from the TCA configuration
  Configuration/TCA/tx_tea_domain_model_product_tea.php
Labels: cleanup

#388 [FEATURE] Add module definitions to the PhpStorm meta file
  .phpstorm.meta.php
Labels: enhancement

#390 [BUGFIX] Fix code coverage calculation after switch to core testing framework
  composer.json
Labels: bug

#381 [FEATURE] Enable php8.1
  .github/workflows/ci.yml
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/php-lint-php8.1.yml
  composer.json
  ext_emconf.php
Labels: enhancement

#391 [CLEANUP] Always have the CI job name as first element
  .github/workflows/ci.yml
  .github/workflows/predefined.yml
Labels: cleanup

#395 [BUGFIX] Fix the trigger syntax in the CI builds
  .github/workflows/predefined.yml
Labels: bug

#394 [BUGFIX] Remove duplicate entry from the code quality CI job
  .github/workflows/ci.yml
Labels: cleanup, blocked

#397 [TASK] Add a description for the `prepare-release` Composer command
  composer.json
Labels: documentation, enhancement

#398 [CLEANUP] Use generics for Prophecy type annotations
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup
