Repository TYPO3BestPractices/tea, pull requests merged in 2022-04, with the labels that each got.

#414 [CLEANUP] Add generics annotation to the Tea repository
  Classes/Domain/Repository/Product/TeaRepository.php
Labels: cleanup

#413 [CLEANUP] Drop an unnecessary field in a test
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#422 [BUGFIX] Use `executeQuery()` in functional test example
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: bug

#404 [DOCS] Update docs
  .editorconfig
  Documentation/ContinuousIntegration.rst
  Documentation/DependencyManager.rst
  Documentation/Documentation.rst
  Documentation/Documentation/Rendering/Index.rst
  Documentation/Environment.rst
  Documentation/Images/SlidesCover.jpg
  Documentation/Images/VideoCover.jpg
  Documentation/Includes.rst.txt
  Documentation/Includes.txt
  Documentation/Index.rst
  Documentation/Introduction.rst
  Documentation/Introduction/Index.rst
  Documentation/Linters/GitHub/Index.rst
  Documentation/Linters/GitLab/Index.rst
  Documentation/Linters/Index.rst
  Documentation/Running.rst
  Documentation/Security.rst
  Documentation/Settings.cfg
  Documentation/Sitemap.rst
  Documentation/TestingFramework.rst
  Documentation/genindex.rst
  README.md
  composer.json
Labels: documentation, enhancement

#423 [CLEANUP] Always use `name` as first key for GitHub Action steps
  .github/workflows/codecoverage.yml
Labels: cleanup

#432 [BUGFIX] Do not cache the `.Build` directory in GitLab CI
  .gitlab/pipeline/jobs/build-composer-dependencies.yml
Labels: bug

#430 [TASK] Switch to the TYPO3 Code of Conduct
  CHANGELOG.md
  CODE_OF_CONDUCT.md
Labels: documentation

#424 [TASK] Sync the GitHub Actions job definitions
  .github/workflows/codecoverage.yml
Labels: cleanup

#425 [FEATURE] Use Coveralls for the code coverage
  .github/workflows/codecoverage.yml
  .gitignore
  CHANGELOG.md
  README.md
  composer.json
Labels: enhancement

#435 [CLEANUP] Make a type annotation in a unit test more specific
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#438 [TASK] Reduce and reorder the badges in the README
  README.md
Labels: documentation

#443 [CLEANUP] Use prepared statements for SQL queries in the tests
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#436 [BUGFIX] Mark the repository test as also covering the model
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: bug
