Repository TYPO3BestPractices/tea, pull requests merged in 2022-09, with the labels that each got.

#541 [TASK] Update to PHIVE 0.15.2
  phive.xml
  tools/phive
Labels: dependencies

#540 [TASK] Upgrade to PHPCOV 6
  phive.xml
  tools/phpcov
Labels: dependencies

#558 [TASK] Make the required system extension versions consistent
  composer.json
  ext_emconf.php
Labels: cleanup

#560 Update ddev to newest version
  .ddev/config.yaml
Labels: cleanup

#559 [BUGFIX] Add hidden files to find in PHP lint
  .phpstorm.meta.php
  composer.json
Labels: bug

#572 [FEATURE] Show the Composer configuration in the CI jobs
  .github/workflows/ci.yml
Labels: enhancement

#585 [TASK] Update ergebnis/composer-normalize
  .github/dependabot.yml
  composer.json
Labels: dependencies

#584 [TASK] Switch Dependabot PR target milestone to the 3.0 milestone
  .github/dependabot.yml
Labels: dependencies

#595 Fix pipeline after dropping php support
  .gitlab/pipeline/jobs/phpcs.yml
  .gitlab/pipeline/jobs/phpstan.yml
Labels: bug

#575 [TASK] Replace switchable controller actions
  CHANGELOG.md
  Configuration/FlexForms/Plugin.xml
  Configuration/TCA/Overrides/tt_content.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/Tea/Index.html
  ext_localconf.php
Labels: cleanup
