Repository TYPO3BestPractices/tea, pull requests merged in 2022-01, with the labels that each got.

#360 [BUGFIX] Fix CI builds for PRs from forks
  .github/workflows/ci.yml
Labels: bug

#367 [CLEANUP] Remove code specific to TYPO3 9LTS
  Tests/Functional/Controller/TeaControllerTest.php
Labels: cleanup

#365 [TASK] Add the TYPO3 Online Days presentation to the README
  README.md
Labels: documentation

#371 [BUGFIX] Avoid php-cs-fixer 3.5.0
  composer.json
Labels: bug

#370 [BUGFIX] Avoid xargs error for empty project
  composer.json
Labels: bug

#372 [TASK] Drop the TYPO3 V9 badge
  CHANGELOG.md
  README.md
Labels: documentation
