Repository TYPO3BestPractices/tea, pull requests merged in 2023-04, with the labels that each got.

#782 [TASK] Bump the TYPO3 12 version from 12.2 to 12.3
  .github/workflows/ci.yml
  .github/workflows/predefined.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-lowest.yml
  composer.json
Labels: dependencies

#787 [FEATURE] Support PHP 8.2
  .github/workflows/ci.yml
  .github/workflows/predefined.yml
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/func-php8.2-v11-highest.yml
  .gitlab/pipeline/jobs/func-php8.2-v11-lowest.yml
  .gitlab/pipeline/jobs/func-php8.2-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.2-v12-lowest.yml
  .gitlab/pipeline/jobs/php-lint-php8.2.yml
  .gitlab/pipeline/jobs/phpcs.yml
  .gitlab/pipeline/jobs/phpstan.yml
  .gitlab/pipeline/jobs/unit-php8.2-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v12-lowest.yml
  composer.json
  ext_emconf.php
Labels: php

#799 [BUGFIX] Do not mock unavailable methods
  Tests/Unit/Controller/TeaControllerTest.php
Labels: bug

#819 [CLEANUP] Reorder the type annotations for better readability
  Classes/Domain/Model/Product/Tea.php
Labels: cleanup

#817 [TASK] Streamline the auto-merge GitHub Actions workflow
  .github/workflows/auto-merge.yml
Labels: cleanup

#818 [FEATURE] Automatically approve Dependabot pull requests
  .github/workflows/auto-approve.yml
Labels: enhancement

#822 [TASK] Bump the TYPO3 12 dependency from ^12.3 to ^12.4
  .github/workflows/ci.yml
  .github/workflows/predefined.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml
  .gitlab/pipeline/jobs/func-php8.2-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.2-v12-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v12-lowest.yml
  composer.json
Labels: dependencies
