Repository TYPO3BestPractices/tea, pull requests merged in 2023-12, with the labels that each got.

#1043 Fix for functional tests on gitlab CI
  .gitlab/build/docker_install.sh
Labels: bug

#1044 [TASK] Add contribution guide
  CONTRIBUTING.md
Labels: documentation

#1052 Remove leftover select_key
  Configuration/TCA/Overrides/tt_content.php
Labels: cleanup

#1058 [BUGFIX] Create required directories before running the functional tests
  composer.json
Labels: bug

#1059 [FOLLOWUP] Fix path of created tests directory
  composer.json
Labels: bug

#1056 [TASK] Drop useless Composer scripts
  composer.json
Labels: make the extension conform to the best practices

#1048 [TASK] Drop the obsolete `app-dir` Composer configuration
  composer.json
Labels: cleanup

#1045 [CLEANUP] Simplify the PHPStan baseline generation script
  composer.json
Labels: cleanup

#1047 [TASK] Drop obsolete Doctrine DBAL development dependency
  composer.json
Labels: cleanup, dependencies

#1065 [TASK] Merge dbms version flags into `-i`
  Build/Scripts/runTests.sh
Labels: task

#1067 Drop obsolete tasks from documentation
  Documentation/Running.rst
Labels: documentation, cleanup

#1070 [TASK] Use only ghcr.io for core-testing images
  Build/Scripts/runTests.sh
Labels: make switch to runTests.sh

#1069 [TASK] Remove `acceptance` test traces from `runTests.sh`
  Build/Scripts/runTests.sh
Labels: cleanup, make switch to runTests.sh

#1073 [TASK] Migrate xliff lint on gitlab
  .gitlab/pipeline/jobs/xliff-lint.yml
Labels: cleanup

#1064 [TASK] Add php8.3 to functional tests gitlab
  .gitlab/pipeline/jobs/func-php8.3-v11-highest.yml
  .gitlab/pipeline/jobs/func-php8.3-v11-lowest.yml
  .gitlab/pipeline/jobs/func-php8.3-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.3-v12-lowest.yml
Labels: task

#1074 [BUGFIX] Avoid JSON-linting the Composer cache directory
  composer.json
Labels: bug

#1076 [TASK] Add `-b` option to select container binary
  Build/Scripts/runTests.sh
Labels: enhancement, make switch to runTests.sh

#1081 [BUGFIX] Use extended `sbuerk/demo-core-testing-*` images
  Build/Scripts/runTests.sh
Labels: bug, make switch to runTests.sh

#1086 [BUGFIX] Use better supported condition checks in `runTests.sh`
  Build/Scripts/runTests.sh
Labels: bug, make switch to runTests.sh

#1089 [BUGFIX] Avoid unsupported option for `podman`
  Build/Scripts/runTests.sh
Labels: bug, make switch to runTests.sh

#1090 [BUGFIX] Ensure removing dangling images works with `podman`
  Build/Scripts/runTests.sh
Labels: bug, make switch to runTests.sh

#1084 [CLEANUP] Autoformat the PHPUnit configuration files
  Tests/Functional/FunctionalTests.xml
  Tests/Unit/UnitTests.xml
Labels: cleanup

#1091 [CLEANUP] Sort the PHPUnit configuration options
  Tests/Functional/FunctionalTests.xml
  Tests/Unit/UnitTests.xml
Labels: cleanup
