Repository TYPO3BestPractices/tea, pull requests merged in 2023-05, with the labels that each got.

#828 [TASK] Make the development dependencies more specific
  composer.json
Labels: dependencies

#831 [FEATURE] Add fix composer normalize command
  composer.json
Labels: cleanup

#829 [TASK] Use anonymous function in TCA overrides
  Configuration/TCA/Overrides/tt_content.php
Labels: cleanup

#751 Make the records localizable
  Configuration/TCA/tx_tea_domain_model_product_tea.php
Labels: enhancement
