Repository TYPO3BestPractices/tea, pull requests merged in 2023-11, with the labels that each got.

#964 [CLEANUP] Make the TYPO3 version switches more consistent
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#963 [CLEANUP] Simplify the mock building in the unit tests
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#962 [TASK] Use more stubs in the unit tests
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#965 [FEATURE] Add support for PHP 8.3
  .github/workflows/ci.yml
  Build/Scripts/runTests.sh
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: enhancement

#960 [TASK] Add Daniel and Łukasz as co-maintainers
  composer.json
  ext_emconf.php
Labels: documentation

#975 [TASK] Remove deprecated license scanning
  .gitlab/pipeline/.gitlab-ci.yml
Labels: cleanup

#974 [BUGFIX] Fix PSR-verify job
  composer.json
Labels: bug

#977 [CLEANUP] Convert one more mock to a stub
  Tests/Unit/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#990 [TASK] Upgrade composer to 2.6 in github actions
  .github/workflows/ci.yml
  .github/workflows/predefined.yml
Labels: cleanup, task

#997 [CLEANUP] Inline some variables in the tests
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#995 [CLEANUP] Use more stubs instead of mocks
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#996 [CLEANUP] Increase the indentation in the DDEV configuration file
  .ddev/config.yaml
Labels: cleanup

#998 [TASK] Migrate DB queries to CSV assertions in the functional tests
  Tests/Functional/Domain/Repository/Fixtures/Product/PersistedTea.csv
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: make the extension conform to the best practices

#993 [TASK] Split up the DB fixtures for the functional tests
  Tests/Functional/Domain/Repository/Fixtures/Product/Tea.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TeaOnPage.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithAllScalarData.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithImage.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithoutOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TwoTeasWithOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TwoUnsortedTeas.csv
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: make the extension conform to the best practices

#1011 [TASK] Remove obsolete symlink for functional tests
  composer.json
Labels: cleanup

#1012 [CLEANUP] Migrate typo3conf path to composer package name
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup, make the extension conform to the best practices, implement changes related to docs

#1013 [TASK] Output the job name in the GitLab CI builds
  .gitlab/pipeline/jobs/func-php7.4-v11-highest.yml
  .gitlab/pipeline/jobs/func-php7.4-v11-lowest.yml
  .gitlab/pipeline/jobs/func-php8.0-v11-highest.yml
  .gitlab/pipeline/jobs/func-php8.0-v11-lowest.yml
  .gitlab/pipeline/jobs/func-php8.1-v11-highest.yml
  .gitlab/pipeline/jobs/func-php8.1-v11-lowest.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml
  .gitlab/pipeline/jobs/func-php8.2-v11-highest.yml
  .gitlab/pipeline/jobs/func-php8.2-v11-lowest.yml
  .gitlab/pipeline/jobs/func-php8.2-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.2-v12-lowest.yml
  .gitlab/pipeline/jobs/unit-php7.4-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php7.4-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.0-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php8.0-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.2-v12-lowest.yml
Labels: bug

#991 [TASK] Upgrade DDEV
  .ddev/config.yaml
Labels: cleanup, task

#989 [FEATURE] Make records timeable and hidable
  CHANGELOG.md
  Configuration/TCA/tx_tea_domain_model_product_tea.php
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang_db.xlf
Labels: enhancement

#1017 [TASK] Add missing test case for fetching none existing tea
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: enhancement, php, make the extension conform to the best practices

#1020 [FEATURE] Provide Polish translation for tea
  CHANGELOG.md
  Resources/Private/Language/pl.locallang.xlf
  Resources/Private/Language/pl.locallang_db.xlf
Labels: enhancement

#1029 [BUGFIX] Remove invalid argument quoting in `runTests.sh`
  Build/Scripts/runTests.sh
Labels: bug, make switch to runTests.sh

#1030 [CLEANUP] Drop extraneous whitespace in a Composer script
  composer.json
Labels: cleanup

#1032 [FEATURE] Add PHP 8.3 lint to GitLab CI
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/php-lint-php8.3.yml
Labels: enhancement, task

#1033 [FEATURE] Add PHP 8.3 unit tests to GitLab CI
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/unit-php8.3-v11-highest.yml
  .gitlab/pipeline/jobs/unit-php8.3-v11-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.3-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.3-v12-lowest.yml
Labels: enhancement, task
