Repository TYPO3BestPractices/tea, pull requests merged in 2023-02, with the labels that each got.

#745 [TASK] Document that this is not a kickstarter package
  Documentation/Introduction.rst
Labels: documentation

#741 [TASK] Explain the extension name
  Documentation/Introduction.rst
Labels: documentation

#746 Upgrade to TYPO3 v12.2
  .github/workflows/ci.yml
  .github/workflows/predefined.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/func-php8.1-v12-lowest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-highest.yml
  .gitlab/pipeline/jobs/unit-php8.1-v12-lowest.yml
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
  composer.json
Labels: cleanup

#756 [FEATURE] Add automerging of green Dependabot PRs
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: enhancement

#740 Add check for PSR-4 namespace correctness
  .github/workflows/ci.yml
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/composer-psr-verify.yml
  composer.json
Labels: enhancement
