Repository TYPO3BestPractices/tea, pull requests merged in 2023-06, with the labels that each got.

#849 Remove obsolete php copy paste check in gitlab CI
  .gitlab/pipeline/.gitlab-ci.yml
Labels: cleanup

#850 [BUGFIX] Add missing PHP extensions in GitLab CI
  .gitlab/build/docker_install.sh
Labels: bug

#855 [TASK] Make the repository tests more fine-grained
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
Labels: cleanup

#856 [TASK] Make the controller tests more fine-grained
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#860 [FEATURE] Add `Tea.ownerUid`
  Classes/Domain/Model/Product/Tea.php
  Classes/Domain/Repository/Product/TeaRepository.php
  Configuration/Extbase/Persistence/Classes.php
  Configuration/TCA/tx_tea_domain_model_product_tea.php
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang_db.xlf
  Tests/Functional/Domain/Repository/Fixtures/Product/Tea.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TeaWithoutOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/Product/TwoTeasWithOwner.csv
  Tests/Functional/Domain/Repository/Product/TeaRepositoryTest.php
  Tests/Unit/Domain/Model/Product/TeaTest.php
  ext_tables.sql
Labels: enhancement

#861 [CLEANUP] Polish the code formatting in the TCA configuration
  Configuration/TCA/tx_tea_domain_model_product_tea.php
Labels: cleanup

#862 [TASK] Drop incorrectly placed `scope` HTML attribute
  Resources/Private/Templates/Tea/Index.html
Labels: cleanup

#866 [FEATURE] Add validation to the FE-editable tea properties
  Classes/Domain/Model/Product/Tea.php
Labels: enhancement

#865 [BUGFIX] Allow `ActionController::redirect` in tests again
  Tests/Unit/Controller/TeaControllerTest.php
Labels: bug

#864 [FEATURE] Add a list view for the FE tea editor
  CHANGELOG.md
  Classes/Controller/FrontEndEditorController.php
  Configuration/TCA/Overrides/tt_content.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Layouts/FrontEndEditor.html
  Resources/Private/Templates/FrontEndEditor/Index.html
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
  ext_localconf.php
Labels: enhancement

#872 [FEATURE] Add FE editing for existing tea records
  Classes/Controller/FrontEndEditorController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/.gitkeep
  Resources/Private/Partials/FrontEndEditor/Form.html
  Resources/Private/Partials/FrontEndEditor/ValidationResult.html
  Resources/Private/Templates/FrontEndEditor/Edit.html
  Resources/Private/Templates/FrontEndEditor/Index.html
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
  ext_localconf.php
Labels: enhancement

#876 [FEATURE] Add a delete functionality for the Tea FE editor
  CHANGELOG.md
  Classes/Controller/FrontEndEditorController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/FrontEndEditor/Index.html
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
  ext_localconf.php
Labels: enhancement

#877 [BUGFIX] Skip validation where validation makes no sense
  Classes/Controller/FrontEndEditorController.php
Labels: bug
