Repository TYPO3BestPractices/tea, pull requests merged in 2024-10, with the labels that each got.

#1480 [TASK] Rework the testing framework section in the docs
  Documentation/Index.rst
  Documentation/ReleaseBranchingStrategy.rst
  Documentation/TestingFramework.rst
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#1484 [TASK] Move a repository test from unit to functional
  Tests/Functional/Domain/Repository/TeaRepositoryTest.php
  Tests/Unit/Domain/Repository/TeaRepositoryTest.php
Labels: hacktoberfest, hacktoberfest-accepted

#1495 [BUGFIX] Fix the image URL of the CI status badge
  README.md
Labels: bug, documentation, hacktoberfest-accepted

#1497 [TASK] Add if condition from core runTests.sh
  Build/Scripts/runTests.sh
Labels: hacktoberfest, runTests.sh, hacktoberfest-accepted

#1502 [DOCS] Add comment for controller unit tests
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
  Tests/Unit/Controller/TeaControllerTest.php
Labels: documentation
