Repository TYPO3BestPractices/tea, pull requests merged in 2024-04, with the labels that each got.

#1208 [BUGFIX] Avoid warnings in PHP 8.2/8.3 with lowest dependencies
  composer.json
Labels: bug, dependencies

#1206 [TASK] Use unique and more realistic test data in the unit tests
  Tests/Unit/Domain/Model/TeaTest.php
Labels: cleanup

#1221 [BUGFIX] Add `resname` to all language labels
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_db.xlf
  Resources/Private/Language/pl.locallang.xlf
  Resources/Private/Language/pl.locallang_db.xlf
Labels: bug

#1225 [TASK] Separate the fixture TypoScript into setup and constants
  Tests/Functional/Controller/Fixtures/TypoScript/Setup/Rendering.typoscript
  Tests/Functional/Controller/TeaControllerTest.php
Labels: cleanup

#1226 [TASK] Reduce the DB fixtures some more
  Tests/Functional/Domain/Repository/Fixtures/TeaWithAllScalarData.csv
  Tests/Functional/Domain/Repository/Fixtures/TeaWithImage.csv
  Tests/Functional/Domain/Repository/Fixtures/TeaWithOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/TeaWithoutOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/TwoTeasWithOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/TwoUnsortedTeas.csv
Labels: cleanup

#1063 [TASK] Drop DDEV configuration
  .ddev/config.yaml
  .ddev/php/custom-php.ini
  .gitattributes
  CHANGELOG.md
  Documentation/Environment.rst
  Documentation/Running.rst
Labels: make switch to runTests.sh

#1242 [CLEANUP] Reduce redundancies in the PHPStan configuration
  phpstan.neon
Labels: cleanup

#1253 [TASK] Drop redundant bootstrap information from PHPStan config
  phpstan.neon
Labels: cleanup, phpstan

#1256 [TASK] allow `assertInstanceOf` checks for PHPStan
  phpstan-baseline.neon
  phpstan.neon
Labels: phpstan

#1259 [TASK] Drop `approved="yes"` from the original locallang files
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_db.xlf
Labels: cleanup
