Repository TYPO3BestPractices/tea, pull requests merged in 2024-09, with the labels that each got.

#1450 [TASK] Unify the coverage-related directories
  .github/workflows/codecoverage.yml
  composer.json
Labels: cleanup

#1448 [TASK] Drop `.phpstorm.meta.php`
  .gitattributes
  .phpstorm.meta.php
Labels: cleanup

#1446 [TASK] Add two new ISSUE_TEMPLATES, feature and task
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/task.md
Labels: enhancement, task

#1453 [TASK] Update the testing framework
  composer.json
Labels: dependencies

#1357 [TASK] Move php sniff to build dir
  .gitattributes
  Build/phpcs/phpcs.xml
  CHANGELOG.md
  composer.json
Labels: cleanup, make the extension conform to the best practices

#1456 [BUGFIX] Fix parallel lint in gitlab CI
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/.composer-update.yml
  .gitlab/pipeline/jobs/php-lint-php7.4.yml
  .gitlab/pipeline/jobs/php-lint-php8.0.yml
  .gitlab/pipeline/jobs/php-lint-php8.1.yml
  .gitlab/pipeline/jobs/php-lint-php8.2.yml
  .gitlab/pipeline/jobs/php-lint-php8.3.yml
Labels: bug

#1457 [BUGFIX] Add node version 20.17.0 to `package.json`
  package.json
Labels: bug

#1458 [TASK] Remove redundancies in the `prepare-release` Composer script
  composer.json
Labels: cleanup

#1460 [BUGFIX] Fix functional php8.2 v12 highest job in GitLab CI
  .gitlab/pipeline/jobs/func-php8.2-v12-highest.yml
Labels: bug

#1463 [TASK] Set npm to version 10.8.2
  package.json
Labels: bug

#1472 [TASK] Add a time limit to the documentation check on CI
  .github/workflows/ci.yml
Labels: bug

#1464 [TASK] Sort the includes for GitLab CI
  .gitlab/pipeline/.gitlab-ci.yml
Labels: cleanup

#1468 [TASK] Bump the Symfony development dependencies
  composer.json
Labels: dependencies

#1475 [TASK] Used fixed versions for most development dependencies
  composer.json
Labels: bug, dependencies

#1459 [FEATURE] Add Composer scripts and a CI job for Rector
  .github/workflows/ci.yml
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/rector.yml
  composer.json
Labels: enhancement, hacktoberfest
