Repository TYPO3BestPractices/tea, pull requests merged in 2024-07, with the labels that each got.

#1352 [TASK] Move tests configuration to Build directory
  Build/phpunit/FunctionalTests.xml
  Build/phpunit/UnitTests.xml
  CHANGELOG.md
  composer.json
Labels: make the extension conform to the best practices, task

#1356 [TASK] Move xliff linter to xliff dir
  Build/xliff/xliff-lint
  CHANGELOG.md
  composer.json
Labels: make the extension conform to the best practices

#1358 [TASK] Sort the list of non-packaged files
  .gitattributes
  composer.json
Labels: cleanup

#1375 [BUGFIX] Use correct path for functional and unit tests
  Build/Scripts/runTests.sh
Labels: bug

#1377 [TASK] Add missing switch, hint to run composer install at beginning
  Documentation/Running.rst
Labels: documentation

#1382 [FEATURE] Include composer-unused to find unused packages
  .gitattributes
  .github/workflows/ci.yml
  composer-unused.php
  composer.json
Labels: enhancement

#1380 [TASK] Allow additional composer options for `-s composerInstall`
  Build/Scripts/runTests.sh
Labels: runTests.sh

#1389 [TASK] Clean up the unit tests configuration
  Build/phpunit/UnitTests.xml
Labels: cleanup

#1395 [BUGFIX] Remove unavailable PHPUnit configuration option
  Build/phpunit/FunctionalTests.xml
  Build/phpunit/UnitTests.xml
Labels: bug

#1390 [FEATURE] Add `composerUnused` suite to `runTests.sh`
  Build/Scripts/runTests.sh
Labels: enhancement, runTests.sh

#1394 [BUGFIX] No longer create not needed temp folder
  Build/Scripts/runTests.sh
Labels: bug, cleanup, runTests.sh

#1401 [BUGFIX] Remove debug echo
  Build/Scripts/runTests.sh
Labels: bug

#1383 [TASK] Remove no longer needed path to binaries
  composer.json
Labels: cleanup

#1399 [TASK] Add more development documentation
  Documentation/Environment.rst
Labels: documentation

#1404 [TASK] Rename npm commands to fit general naming scheme
  .github/workflows/ci.yml
  .gitlab/pipeline/jobs/javascript-lint.yml
  package.json
Labels: cleanup

#1378 [FEATURE] Use parallel-lint for command ci:php:lint
  .github/workflows/ci.yml
  composer.json
Labels: enhancement

#1406 [TASK] Rename the CSS lint npm command
  .github/workflows/ci.yml
  .gitlab/pipeline/jobs/javascript-lint.yml
  package.json
Labels: cleanup

#1396 [FEATURE] Allow running npm based quality checks via `runTests.sh`
  Build/Scripts/runTests.sh
Labels: enhancement

#1407 [BUGFIX] Remove none existing cglFix
  Build/Scripts/runTests.sh
Labels: cleanup

#1408 [TASK] Tackle shellcheck issues
  Build/Scripts/runTests.sh
Labels: cleanup

#1391 [FEATURE] Add PHP mess detector
  .github/workflows/ci.yml
  Build/phpmd/phpmd.xml
  composer.json
Labels: enhancement

#1400 [FEATURE] Add shellcheck to Github pipeline
  .github/workflows/ci.yml
  Build/Scripts/runTests.sh
Labels: github_actions, feature

#1413 [FEATURE] Add support for PHP 8.4 in `runTests.sh`
  Build/Scripts/runTests.sh
Labels: runTests.sh

#1414 [FEATURE] Show memory consumption of phpstan
  composer.json
Labels: enhancement, runTests.sh

#1411 [BUGFIX] Clean up network after invalid command
  Build/Scripts/runTests.sh
Labels: bug, runTests.sh
