Repository TYPO3BestPractices/tea, pull requests merged in 2024-01, with the labels that each got.

#1104 [CLEANUP] Sort the files/directories in the `prepare-release` script
  composer.json
Labels: cleanup

#1116 [TASK] Migrate the deprecated `executeFrontendRequest` in tests
  Tests/Functional/Controller/TeaControllerTest.php
Labels: make the extension conform to the best practices

#1025 [!!!][TASK] Drop additional namespace segment for the Tea model
  CHANGELOG.md
  Classes/Controller/FrontEndEditorController.php
  Classes/Controller/TeaController.php
  Classes/Domain/Model/Tea.php
  Classes/Domain/Repository/TeaRepository.php
  Configuration/Extbase/Persistence/Classes.php
  Configuration/TCA/tx_tea_domain_model_tea.php
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang_db.xlf
  Resources/Private/Language/pl.locallang_db.xlf
  Tests/Functional/Controller/Fixtures/Database/Teas.csv
  Tests/Functional/Domain/Repository/Fixtures/PersistedTea.csv
  Tests/Functional/Domain/Repository/Fixtures/TeaOnPage.csv
  Tests/Functional/Domain/Repository/Fixtures/TeaWithAllScalarData.csv
  Tests/Functional/Domain/Repository/Fixtures/TeaWithImage.csv
  Tests/Functional/Domain/Repository/Fixtures/TeaWithOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/TeaWithoutOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/TwoTeasWithOwner.csv
  Tests/Functional/Domain/Repository/Fixtures/TwoUnsortedTeas.csv
  Tests/Functional/Domain/Repository/TeaRepositoryTest.php
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
  Tests/Unit/Controller/TeaControllerTest.php
  Tests/Unit/Domain/Model/TeaTest.php
  Tests/Unit/Domain/Repository/TeaRepositoryTest.php
  ext_tables.sql
Labels: make the extension conform to the best practices

#1135 [TASK] Avoid unnecessary FQCN
  Tests/Unit/Domain/Model/TeaTest.php
Labels: cleanup

#1134 [BUGFIX] Use our own PHPUnit configuration files in `runTests.sh`
  Build/Scripts/runTests.sh
Labels: bug, make switch to runTests.sh

#1133 [TASK] Rework a test communicate its purpose more clearly
  Tests/Functional/Domain/Repository/TeaRepositoryTest.php
Labels: cleanup

#1136 [TASK] Prefer string casts over explictly calling `__toString`
  Tests/Functional/Controller/TeaControllerTest.php
Labels: cleanup

#1137 [TASK] Consistently quote string values in fixture CSV files
  Tests/Functional/Controller/Fixtures/Database/ContentElementTeaIndex.csv
  Tests/Functional/Controller/Fixtures/Database/SiteStructure.csv
Labels: cleanup

#1145 [TASK] Update php to 8.3 on ddev by default
  .ddev/config.yaml
Labels: cleanup

#1144 [TASK] Change webdir of TYPO3 to public
  Build/Scripts/runTests.sh
  composer.json
Labels: make the extension conform to the best practices
