Repository TYPO3BestPractices/tea, pull requests merged in 2025-02, with the labels that each got.

#1573 [TASK] Update `symfony/yaml`
  composer.json
Labels: dependencies

#1581 [TASK] Make the naming schema of CI jobs consistent
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/func-v12-php8.1-highest.yml
  .gitlab/pipeline/jobs/func-v12-php8.1-lowest.yml
  .gitlab/pipeline/jobs/func-v12-php8.2-highest.yml
  .gitlab/pipeline/jobs/func-v12-php8.2-lowest.yml
  .gitlab/pipeline/jobs/func-v12-php8.3-highest.yml
  .gitlab/pipeline/jobs/func-v12-php8.3-lowest.yml
  .gitlab/pipeline/jobs/unit-v12-php8.1-highest.yml
  .gitlab/pipeline/jobs/unit-v12-php8.1-lowest.yml
  .gitlab/pipeline/jobs/unit-v12-php8.2-highest.yml
  .gitlab/pipeline/jobs/unit-v12-php8.2-lowest.yml
  .gitlab/pipeline/jobs/unit-v12-php8.3-highest.yml
  .gitlab/pipeline/jobs/unit-v12-php8.3-lowest.yml
Labels: cleanup

#1583 [TASK] Drop support for Symfony 5.x
  composer.json
Labels: dependencies

#1536 [FEATURE] Add support for PHP 8.4
  .github/workflows/ci.yml
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/func-v12-php8.4-highest.yml
  .gitlab/pipeline/jobs/func-v12-php8.4-lowest.yml
  .gitlab/pipeline/jobs/php-lint-php8.4.yml
  .gitlab/pipeline/jobs/unit-v12-php8.4-highest.yml
  CHANGELOG.md
  composer.json
  ext_emconf.php
  rector.php
Labels: enhancement

#1388 [DOCS] Extend PHIVE section in docs
  Documentation/DependencyManager.rst
Labels: documentation

#1590 [TASK] Simplify some type annotations
  Classes/Domain/Model/Tea.php
Labels: cleanup

#1591 [BUGFIX] Fix GitLab CI job dependencies
  .gitlab/pipeline/jobs/php-cs-fixer.yml
  .gitlab/pipeline/jobs/phpstan.yml
  .gitlab/pipeline/jobs/rector.yml
Labels: bug

#1592 [BUGFIX] Improve type safety for lazy-loaded associations
  Classes/Domain/Model/Tea.php
  Tests/Functional/Domain/Repository/Fixtures/propertyMapping/TeaWithDeletedImage.csv
  Tests/Functional/Domain/Repository/TeaRepositoryTest.php
Labels: bug
