Repository TYPO3BestPractices/tea, pull requests merged in 2025-04, with the labels that each got.

#1635 [BUGFIX] Generate the PHPStan baseline in `Build/`
  composer.json
Labels: bug

#1631 [BUGFIX] Delete current configuration files with `prepare-release`
  composer.json
Labels: bug

#1630 [FEATURE] Test the `prepare-release` Composer script on CI
  .github/workflows/ci.yml
  .gitlab/pipeline/.gitlab-ci.yml
  .gitlab/pipeline/jobs/prepare-release.yml
Labels: enhancement

#1644 [TASK] Remove no longer needed Controller unit test
  Tests/Unit/Controller/TeaControllerTest.php
Labels: cleanup

#1642 [TASK] Cover empty tea index with functional test
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/Tea/Index.html
  Tests/Functional/Controller/TeaControllerTest.php
Labels: feature

#1646 [TASK] Shorten the GitHub Actions CI job label
  .github/workflows/ci.yml
Labels: documentation

#1643 [FEATURE] Add proper 404 handling for tea detail action
  Classes/Controller/TeaController.php
  Tests/Functional/Controller/TeaControllerTest.php
  composer-unused.php
Labels: feature

#1651 [FEATURE] Move the tea index configuration to FlexForms
  Configuration/FlexForms/TeaIndex.xml
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TypoScript/constants.typoscript
  Configuration/TypoScript/setup.typoscript
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Tests/Functional/Controller/Fixtures/Database/ContentElementTeaIndex.csv
  Tests/Functional/Controller/Fixtures/Database/SiteStructure.csv
  Tests/Functional/Controller/Fixtures/Database/TeaInSubfolder.csv
  Tests/Functional/Controller/Fixtures/TypoScript/Constants/PluginConfiguration.typoscript
  Tests/Functional/Controller/TeaControllerTest.php
Labels: enhancement
