Repository TYPO3BestPractices/tea, pull requests merged in 2025-01, with the labels that each got.

#1535 [BUGFIX] Avoid unsetting almost all PHP-CS-Fixes rules
  .php-cs-fixer.php
Labels: bug

#1537 [TASK] Update the Symfony development dependencies
  composer.json
Labels: dependencies

#1538 [TASK] Update the development dependencies
  composer.json
Labels: dependencies

#1540 [TASK] Raise the minimum required bugfix version for TYPO3
  composer.json
  ext_emconf.php
  rector.php
Labels: dependencies

#1419 [TASK] Add functional tests for `showAction`
  Tests/Functional/Controller/Fixtures/Database/ContentElementTeaIndex.csv
  Tests/Functional/Controller/Fixtures/Database/SiteStructure.csv
  Tests/Functional/Controller/TeaControllerTest.php
Labels: setup functional tests for requests

#1553 [TASK] Improve readability of php-cs-fixer configuration
  .php-cs-fixer.php
Labels: cleanup

#1353 [TASK] Move php-cs-fixer to Build dir
  .gitattributes
  Build/php-cs-fixer/php-cs-fixer.php
  CHANGELOG.md
  composer.json
Labels: make the extension conform to the best practices
